spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Webkit?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: alsrb!5606
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  dir: /Users/songmingyu/Webkit/
logging:
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
      max-history: 7
      max-file-size: 5KB
      total-size-cap: 1MB
  file:
    name: logs/log
  level:
    com.blog.tistory: info


